#' Visualize signature scores across experimental groups
#'
#' Generates boxplots of Cellsemble signature scores across sample groups.
#' The function provides a visual representation of the distribution of
#' user-selected biological signatures and optionally integrates statistical
#' results obtained from \code{\link{cellsemble_compare}}.
#'
#' @param x A \code{cellsemble_result} object generated by one of the
#'   Cellsemble scoring functions, including \code{\link{cellsemble_epic_run}},
#'   \code{\link{cellsemble_xcell_run}},
#'   \code{\link{cellsemble_mcp_run}}, or
#'   \code{\link{cellsemble_custom_run}}.
#' @param signature Character string indicating the signature to visualize.
#'   Must correspond to one of the signatures available in
#'   \code{x$signatures}.
#' @param group_col Character string specifying the metadata column used to
#'   define sample groups. Default is \code{"Group"}.
#' @param compare_obj Optional \code{cellsemble_compare} object generated by
#'   \code{\link{cellsemble_compare}}. When provided, statistical results are
#'   displayed together with the visualization.
#' @param show_points Logical. If \code{TRUE}, individual sample points are
#'   displayed over the boxplot.
#'
#' @return
#' An object of class \code{cellsemble_boxplot} containing:
#' \itemize{
#'   \item The generated ggplot object.
#'   \item The plotting data table.
#'   \item The selected signature and grouping variable.
#'   \item Statistical information when available.
#'   \item Plot configuration parameters.
#' }
#'
#' @details
#' Cellsemble signatures represent sample-level scores derived from
#' deconvolution methods or custom gene signatures. This function allows
#' users to inspect how these scores are distributed across experimental
#' groups.
#'
#' If a \code{cellsemble_compare} object is provided, adjusted p-values,
#' mean differences and effect sizes are extracted and displayed on the plot.
#' Statistical annotations are based on the multiple-testing corrected
#' results generated during the comparison step.
#'
#' Individual points can be displayed to preserve sample-level information,
#' which is particularly useful for transcriptomic datasets where biological
#' variability between samples may be substantial.
#'
#' @examples
#' \dontrun{
#' # Run a Cellsemble scoring method
#'
#' result <- cellsemble_custom_run(
#'   project = proj,
#'   signatures = signatures
#' )
#'
#' # Plot a signature distribution
#'
#' box <- cellsemble_boxplot(
#'   result,
#'   signature = "Lymphocytes",
#'   group_col = "Group"
#' )
#'
#' # Add statistical comparison results
#'
#' comparison <- cellsemble_compare(
#'   result,
#'   group_col = "Group"
#' )
#'
#' box <- cellsemble_boxplot(
#'   result,
#'   signature = "Lymphocytes",
#'   compare_obj = comparison
#' )
#'}
#'
#' @seealso
#' \code{\link{cellsemble_compare}},
#' \code{\link{cellsemble_delta}},
#' \code{\link{cellsemble_association}},
#' \code{\link{cellsemble_custom_run}}
#'
#' @export

cellsemble_boxplot <- function(
    x,
    signature,
    group_col = "Group",
    compare_obj = NULL,
    show_points = TRUE
) {

  # -------------------------
  # 1. Get data
  # -------------------------
  df <- x$scores

  # -------------------------
  # 2. Validate input
  # -------------------------
  if (!inherits(x, "cellsemble_result")) {
    stop("Input must be a 'cellsemble_result'")
  }

  if (!is.character(signature) || length(signature) != 1) {
    stop("'signature' must be a single character name present in x$signatures")
  }

  if (is.null(x$signatures) || !signature %in% names(x$signatures)) {
    stop(paste0("signature '", signature, "' not found in x$signatures"))
  }

  if (!signature %in% names(x$signatures)) {
    stop("signature not found")
  }

  if (!group_col %in% colnames(df)) {
    stop("group_col not found")
  }

  if (!is.null(compare_obj)) {
    if (!inherits(compare_obj, "cellsemble_compare")) {
      warning("compare object is not 'cellsemble_compare'")
    }
  }

  # -------------------------
  # 3. Build plotting data
  # -------------------------
  plot_df <- data.frame(
    sample = df$sample,
    group  = df[[group_col]],
    score  = df[[signature]]
  )

  # -------------------------
  # 4. Extract statistics
  # -------------------------
  subtitle <- NULL
  signif_label <- NULL
  stat_row <- NULL

  if (!is.null(compare_obj)) {

    stat_row <- compare_obj$results[
      compare_obj$results$signature == signature,
    ]

    if (nrow(stat_row) > 0) {

      p_value <- stat_row$p_adj
      mean_diff <- stat_row$difference
      effect_size <- stat_row$effect_size

      # --- significance stars ---
      signif_label <- if (p_value < 0.001) {
        "***"
      } else if (p_value < 0.01) {
        "**"
      } else if (p_value < 0.05) {
        "*"
      } else {
        "ns"
      }

      # --- p-value label ---
      p_label_sub <- if (p_value < 0.001) {
        "< 0.001"
      } else {
        formatC(p_value, format = "f", digits = 3)
      }

      # --- subtitle ---
      subtitle <- paste0(
        "diff = ",
        round(mean_diff, 2),
        " | p ",
        ifelse(p_value < 0.001, "", "= "),
        p_label_sub
      )
    }
  }

  # -------------------------
  # 5. Plot
  # -------------------------
  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop("Please install 'ggplot2'")
  }

  p <- ggplot2::ggplot(
    plot_df,
    ggplot2::aes(
      x = .data$group,
      y = .data$score,
      fill = .data$group
    )
  ) +

    ggplot2::geom_boxplot(
      alpha = 0.75,
      outlier.shape = NA,
      width = 0.7,
      linewidth = 0.7
    )

  # -------------------------
  # 6. Optional points
  # -------------------------
  if (show_points) {

    p <- p +
      ggplot2::geom_point(
        ggplot2::aes(color = .data$group),
        position = ggplot2::position_jitter(width = 0.1),
        shape = 21,
        color = "black",
        size = 1.8,
        alpha = 0.1
      )
  }

  # -------------------------
  # 7. Labels and theme
  # -------------------------
  p <- p +

    ggplot2::labs(
      title = signature,
      subtitle = subtitle,
      x = NULL,
      y = "Gene set score"
    ) +

    ggplot2::theme_bw(base_size = 12) +

    ggplot2::theme(
      legend.position = "none",
      axis.text.x = ggplot2::element_text(
        angle = 45,
        hjust = 1
      ),
      axis.title.y = ggplot2::element_text(
        margin = ggplot2::margin(r = 12)
      )
    )

  # -------------------------
  # 8. Significance annotation
  # -------------------------
  if (!is.null(signif_label)) {

    p <- p +
      ggplot2::annotation_custom(
        grid::textGrob(
          label = signif_label,
          x = 0.5,
          y = 0.92,
          gp = grid::gpar(
            col = "grey20",
            fontsize = 16,
            fontface = "bold"
          )
        )
      )
  }

  # -------------------------
  # 9. Print plot
  # -------------------------
  print(p)

  # -------------------------
  # 10. Output
  # -------------------------

  obj <- list(

    # core
    plot = p,
    plot_data = plot_df,

    # metadata
    signature = signature,
    group_col = group_col,

    # statistics
    statistics = stat_row,

    # annotations
    subtitle = subtitle,
    significance = signif_label,

    # plot settings
    params = list(
      show_points = show_points
    )

  )

  class(obj) <- "cellsemble_boxplot"

  # -------------------------
  # 11. Console summary
  # -------------------------
  .print_header("Cellsemble Boxplot")

  .print_block("Gene set", function() {

    cat("Gene set:            ", signature, "\n")
    cat("Groups:              ",
        paste(unique(plot_df$group), collapse = " vs "),
        "\n")
  })

  if (!is.null(compare_obj) && exists("stat_row")) {

    .print_block("Statistics", function() {

      cat("Mean difference:     ",
          round(stat_row$difference, 3),
          "\n")

      cat("Effect size (d):     ",
          round(stat_row$effect_size, 3),
          "\n")

      cat("95% CI:               [",
          round(stat_row$ci_low, 3),
          ", ",
          round(stat_row$ci_high, 3),
          "]\n", sep = "")

      cat("Adjusted p-value:    ",
          formatC(stat_row$p_adj,
                  format = "e",
                  digits = 2),
          "\n")
    })
  }

  .print_block("Group means", function() {

    means <- stats::aggregate(
      plot_df["score"],
      by = list(group = plot_df$group),
      FUN = mean
    )

    print(means, row.names = FALSE)
  })

  # -------------------------
  # 12. Return
  # -------------------------
  return(invisible(obj))
}
