#' Visualize global patterns of cell signature scores using dimensionality reduction
#'
#' Performs dimensionality reduction on cell signature scores generated by
#' \code{cellsemble} and provides PCA or UMAP visualizations of sample-level
#' cellular composition or biological program patterns. Unlike expression-based
#' dimensionality reduction methods, this function operates on previously
#' calculated signature scores, enabling intuitive exploration of relationships
#' between samples based on inferred cellular features.
#'
#' @param x A \code{cellsemble_result} object generated by
#'   \code{cellsemble_*_run()} functions, containing sample-level signature
#'   scores.
#' @param method Dimensionality reduction method. Options are
#'   \code{"pca"} (default) or \code{"umap"}.
#' @param group_col Character string specifying the metadata column used to
#'   color samples. Default is \code{"Group"}.
#' @param scale Logical. If \code{TRUE}, signature scores are standardized
#'   before dimensionality reduction.
#' @param n_neighbors Number of neighbors used by UMAP. If \code{NULL},
#'   an adaptive value based on sample size is selected.
#' @param add_ellipse Logical. If \code{TRUE}, confidence ellipses are added
#'   to group visualization when sufficient samples are available.
#' @param ellipse_level Confidence level used for ellipse calculation.
#'   Default is \code{0.95}.
#' @param point_size Numeric value controlling sample point size.
#' @param alpha Numeric transparency value for sample points.
#' @param seed Optional random seed for reproducible UMAP coordinates.
#' @param verbose Logical. If \code{TRUE}, prints progress messages and
#'   summary information.
#'
#' @return
#' An object of class \code{cellsemble_dimred} containing:
#' \itemize{
#'   \item The signature score matrix used for dimensionality reduction.
#'   \item Sample metadata and group information.
#'   \item PCA model, coordinates, explained variance and visualization.
#'   \item UMAP model and coordinates when \code{method = "umap"}.
#'   \item Analysis parameters.
#' }
#'
#' @details
#' Dimensionality reduction is performed using the signature scores stored in
#' the \code{cellsemble_result} object. Each sample is represented by its
#' inferred cellular signatures or biological programs, allowing visualization
#' of similarities between samples based on these features.
#'
#' For PCA, scores are centered and optionally scaled before calculating
#' principal components. The proportion of variance explained by each component
#' is returned together with the coordinates.
#'
#' For UMAP, the dimensionality reduction is performed using the \code{umap}
#' package. Since UMAP is stochastic, providing \code{seed} is recommended for
#' reproducible results.
#'
#' Ellipses represent approximate group-level dispersion and are only added
#' when all groups contain enough samples for reliable estimation.
#'
#' @examples
#' \dontrun{
#'
#' # Run dimensionality reduction using signature scores
#' res_dim <- cellsemble_dimred(
#'   x = res,
#'   method = "pca"
#' )
#'
#' # Generate UMAP visualization
#' res_umap <- cellsemble_dimred(
#'   x = res,
#'   method = "umap",
#'   seed = 123
#' )
#'}
#'
#' @seealso
#' \code{\link{cellsemble_compare}},
#' \code{\link{cellsemble_association}},
#' \code{\link{cellsemble_boxplot}},
#' \code{\link{cellsemble_delta}}
#'
#' @export

cellsemble_dimred <- function(
    x,
    method = c("pca", "umap"),
    group_col = "Group",
    scale = TRUE,
    n_neighbors = NULL,
    add_ellipse = FALSE,
    ellipse_level = 0.95,
    point_size = 2,
    alpha = 0.8,
    seed = NULL,
    verbose = TRUE
) {

  method <- match.arg(method)

  # -------------------------
  # 1. Validate input
  # -------------------------
  if (!inherits(x, "cellsemble_result")) {
    stop(
      "Input must be a 'cellsemble_result'. ",
      "Run cellsemble_run() first."
    )
  }

  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop("Please install 'ggplot2'")
  }

  if (method == "umap") {

    if (!requireNamespace("umap", quietly = TRUE)) {
      stop("Please install 'umap'")
    }
  }

  # -------------------------
  # 2. Get data
  # -------------------------
  df <- x$scores
  signatures <- names(x$signatures)

  if (length(signatures) < 2) {
    stop(
      "At least 2 gene sets are required ",
      "for dimensionality reduction."
    )
  }

  if (!group_col %in% colnames(df)) {
    stop(
      "group_col not found in scores data"
    )
  }

  # -------------------------
  # 3. Build matrix
  # -------------------------
  mat <- as.matrix(
    df[, signatures, drop = FALSE]
  )

  rownames(mat) <- df$sample

  # -------------------------
  # 4. Optional scaling
  # -------------------------
  if (scale) {

    mat <- scale(mat)
  }

  # -------------------------
  # 5. Metadata
  # -------------------------
  groups <- as.factor(df[[group_col]])
  samples <- df$sample

  # -------------------------
  # 6. Ellipse layer
  # -------------------------
  ellipse_layer <- NULL

  if (add_ellipse) {

    group_sizes <- table(groups)

    if (all(group_sizes >= 3)) {

      ellipse_layer <- ggplot2::stat_ellipse(
        ggplot2::aes(fill = .data$Group),
        geom = "polygon",
        alpha = 0.15,
        level = ellipse_level,
        color = NA
      )

    } else if (verbose) {

      message(
        "[cellsemble_dimred] ",
        "Ellipse skipped: at least one group has < 3 samples."
      )
    }
  }

  # -------------------------
  # 7. PCA
  # -------------------------
  if (verbose) {
    message("[cellsemble_dimred] Running PCA...")
  }

  pca_res <- stats::prcomp(
    mat,
    center = TRUE,
    scale. = FALSE
  )

  var_explained <- (
    pca_res$sdev^2 /
      sum(pca_res$sdev^2)
  )

  df_pca <- data.frame(
    Dim1 = pca_res$x[, 1],
    Dim2 = pca_res$x[, 2],
    Group = groups,
    Sample = samples
  )

  p_pca <- ggplot2::ggplot(
    df_pca,
    ggplot2::aes(
      x = .data$Dim1,
      y = .data$Dim2,
      color = .data$Group
    )
  ) +

    ellipse_layer +

    ggplot2::geom_point(
      size = point_size,
      alpha = alpha
    ) +

    ggplot2::scale_fill_discrete() +

    ggplot2::theme_minimal(
      base_size = 12
    ) +

    ggplot2::labs(
      title = "Cellsemble PCA",
      x = paste0(
        "PC1 (",
        round(100 * var_explained[1], 1),
        "%)"
      ),
      y = paste0(
        "PC2 (",
        round(100 * var_explained[2], 1),
        "%)"
      )
    )

  # -------------------------
  # 8. UMAP
  # -------------------------
  p_umap <- NULL
  umap_res <- NULL
  df_umap <- NULL

  if (method == "umap") {

    if (!is.null(seed)) {
      set.seed(seed)
    }

    n_samples <- nrow(mat)

    if (
      is.null(n_neighbors) ||
      n_neighbors >= n_samples
    ) {

      n_neighbors <- max(
        2,
        floor(n_samples / 2)
      )
    }

    if (verbose) {

      message(
        "[cellsemble_dimred] Running UMAP..."
      )
    }

    umap_res <- umap::umap(
      mat,
      n_neighbors = n_neighbors,
      init = "random"
    )

    df_umap <- data.frame(
      Dim1 = umap_res$layout[, 1],
      Dim2 = umap_res$layout[, 2],
      Group = groups,
      Sample = samples
    )

    p_umap <- ggplot2::ggplot(
      df_umap,
      ggplot2::aes(
        x = .data$Dim1,
        y = .data$Dim2,
        color = .data$Group
      )
    ) +

      ellipse_layer +

      ggplot2::geom_point(
        size = point_size,
        alpha = alpha
      ) +

      ggplot2::theme_minimal(
        base_size = 12
      ) +

      ggplot2::labs(
        title = "Cellsemble UMAP",
        x = "UMAP1",
        y = "UMAP2"
      )
  }

  # -------------------------
  # 9. Print plots
  # -------------------------
  if (verbose) {

    print(p_pca)

    if (!is.null(p_umap)) {
      print(p_umap)
    }
  }

  # -------------------------
  # 10. Output
  # -------------------------
  obj <- list(

    matrix = mat,

    metadata = data.frame(
      Sample = samples,
      Group = groups
    ),

    PCA = list(
      model = pca_res,
      coordinates = df_pca,
      variance_explained = var_explained,
      plot = p_pca
    ),

    UMAP = if (method == "umap") list(
      model = umap_res,
      coordinates = df_umap,
      n_neighbors = n_neighbors,
      plot = p_umap
    ) else NULL,

    params = list(
      method = method,
      scale = scale,
      group_col = group_col,
      n_neighbors = n_neighbors,
      add_ellipse = add_ellipse,
      ellipse_level = ellipse_level,
      point_size = point_size,
      alpha = alpha,
      seed = seed
    )
  )

  class(obj) <- "cellsemble_dimred"

  # -------------------------
  # 11. Console summary
  # -------------------------
  .print_header(
    "Cellsemble Dimensionality Reduction"
  )

  .print_block("Summary", function() {

    cat(
      "Method:             ",
      method,
      "\n"
    )

    cat(
      "Samples:            ",
      nrow(mat),
      "\n"
    )

    cat(
      "Gene sets:          ",
      ncol(mat),
      "\n"
    )

    cat(
      "Grouping column:    ",
      group_col,
      "\n"
    )

    cat(
      "Scaling applied:    ",
      scale,
      "\n"
    )

    cat(
      "PC1 variance:       ",
      round(
        100 * var_explained[1],
        2
      ),
      "%\n"
    )

    cat(
      "PC2 variance:       ",
      round(
        100 * var_explained[2],
        2
      ),
      "%\n"
    )

    if (method == "umap") {

      cat(
        "UMAP neighbors:     ",
        n_neighbors,
        "\n"
      )
    }
  })

  # -------------------------
  # 12. Return
  # -------------------------
  return(invisible(obj))
}
