#' Evaluate associations between cell signatures and molecular features
#'
#' Computes pairwise correlations between cell signatures, custom biological
#' programs, and optionally selected genes from a \code{cellsemble_result}
#' object. Evaluates associations among cell composition estimates,
#' custom gene signatures, and individual genes using correlation-based
#' approaches, allowing exploration of relationships between inferred
#' cell populations and molecular signals.
#'
#' The resulting correlation matrix can be visualized as a clustered heatmap,
#' with optional significance annotations.
#'
#' @param x An object of class \code{cellsemble_result} generated by a
#'   Cellsemble scoring function.
#' @param genes Optional character vector containing gene symbols to include in
#'   the association analysis. Genes are extracted from the stored expression
#'   matrix and combined with cell signatures.
#' @param group Optional character vector specifying one or more groups to
#'   include in the analysis. Samples are filtered according to the
#'   \code{Group} metadata column.
#' @param method Correlation method. Options are \code{"pearson"} or
#'   \code{"spearman"}.
#' @param plot Logical. If \code{TRUE}, generates a correlation heatmap.
#' @param scale Logical. If \code{TRUE}, features are standardized before
#'   association analysis.
#' @param show_significance Logical. If \code{TRUE}, statistical significance
#'   labels are displayed on the heatmap.
#' @param triangle Character string indicating which part of the correlation
#'   matrix should be displayed. Options are \code{"lower"}, \code{"upper"},
#'   or \code{"full"}.
#' @param cluster Logical. If \code{TRUE}, hierarchical clustering is applied
#'   to reorder features based on correlation similarity.
#' @param alpha Significance threshold used to determine correlation
#'   significance labels.
#'
#' @return
#' An object of class \code{cellsamble_association} containing:
#' \itemize{
#'   \item Correlation matrix between analyzed features.
#'   \item Feature matrix used for correlation calculation.
#'   \item Feature annotation indicating signatures and genes.
#'   \item Analysis parameters.
#' }
#'
#' @details
#' By default, the function evaluates associations between all signatures
#' available in the \code{cellsemble_result} object. Additional genes can be
#' included when the original expression matrix is available by setting
#' \code{store_matrix = TRUE} during score generation.
#'
#' Associations are calculated using pairwise complete observations. When
#' \code{cluster = TRUE}, hierarchical clustering based on correlation
#' similarity is applied to reorder the matrix for visualization.
#'
#' P-values are calculated for each association and can be displayed as
#' significance labels in the heatmap. Because multiple correlations are
#' evaluated simultaneously, significance values should be interpreted in the
#' context of exploratory analyses.
#'
#' Although Pearson and Spearman coefficients are used internally, this function
#' is referred to as an association analysis because it integrates heterogeneous
#' biological features, including cell scores, gene signatures and individual
#' genes.
#'
#' @seealso
#' \code{\link{cellsemble_compare}},
#' \code{\link{cellsemble_boxplot}},
#' \code{\link{cellsemble_custom_run}},
#' \code{\link{cellsemble_epic_run}},
#' \code{\link{cellsemble_mcp_run}},
#' \code{\link{cellsemble_xcell_run}}
#'
#' @export

cellsemble_association <- function(x,
                                   genes = NULL,
                                   group = NULL,
                                   method = c("pearson", "spearman"),
                                   plot = TRUE,
                                   scale = FALSE,
                                   show_significance = TRUE,
                                   triangle = c("lower", "upper", "full"),
                                   cluster = TRUE,
                                   alpha = 0.05
                                   ) {

  method <- match.arg(method)
  triangle <- match.arg(triangle)

  # -------------------------
  # 1. Get data
  # -------------------------
  scores <- x$scores
  signatures <- names(x$signatures)

  # -------------------------
  # 2. Validate input
  # -------------------------
  if (!inherits(x, "cellsemble_result")) {
    stop("Input must be a 'cellsemble_result'")
  }

  if (length(signatures) == 0) {
    stop("No gene sets found")
  }

  if (!is.null(genes)) {

    if (is.null(x$score_matrix)) {
      stop(
        "Expression matrix not found in object. ",
        "Re-run cellsemble_run(store_matrix = TRUE)"
      )
    }
  }

  # -------------------------
  # 3. Group filtering
  # -------------------------
  if (!is.null(group)) {

    if (!"Group" %in% colnames(scores)) {

      stop(
        "Column 'Group' not found in score table."
      )
    }

    scores <- scores[
      scores$Group %in% group,
      ,
      drop = FALSE
    ]

    if (nrow(scores) == 0) {

      stop(
        "No samples found for selected group(s)."
      )
    }
  }

  # -------------------------
  # 4. Build feature matrix
  # -------------------------
  mat <- scores[, signatures, drop = FALSE]

  annotation <- data.frame(
    feature = colnames(mat),
    type = "gene_set"
  )

  # -------------------------
  # 5. Add genes (optional)
  # -------------------------
  if (!is.null(genes)) {

    expr <- x$score_matrix

    missing_genes <- setdiff(
      genes,
      rownames(expr)
    )

    if (length(missing_genes) > 0) {

      warning(
        "Genes not found: ",
        paste(missing_genes, collapse = ", ")
      )
    }

    valid_genes <- intersect(
      genes,
      rownames(expr)
    )

    if (length(valid_genes) > 0) {

      gene_mat <- t(
        expr[valid_genes, , drop = FALSE]
      )

      gene_mat <- as.data.frame(gene_mat)

      mat <- cbind(mat, gene_mat)

      annotation <- rbind(
        annotation,
        data.frame(
          feature = valid_genes,
          type = "gene"
        )
      )
    }
  }

  # -------------------------
  # 6. Optional scaling
  # -------------------------
  if (scale) {

    mat <- scale(mat)
  }

  # -------------------------
  # 7. Correlation matrix
  # -------------------------
  corr_mat <- stats::cor(
    mat,
    method = method,
    use = "pairwise.complete.obs"
  )

  # -------------------------
  # 8. Correlation p-values
  # -------------------------
  p_mat <- .cor_pmat(
    mat,
    method = method
  )

  # -------------------------
  # 9. Clustering
  # -------------------------
  if (cluster) {

    ord <- stats::hclust(
      stats::dist(1- corr_mat)
    )$order

    corr_mat <- corr_mat[ord, ord]
    p_mat <- p_mat[ord, ord]
  }

  # -------------------------
  # 10. Prepare long format table
  # -------------------------
  corr_df <- data.frame(
    feature1 = rownames(corr_mat)[row(corr_mat)],
    feature2 = colnames(corr_mat)[col(corr_mat)],
    cor = as.vector(corr_mat),
    pval = as.vector(p_mat)
  )

  # -------------------------
  # 11. Keep only selected triangle
  # -------------------------
  if (triangle != "full") {

    corr_df$row_id <- match(
      corr_df$feature1,
      rownames(corr_mat)
    )

    corr_df$col_id <- match(
      corr_df$feature2,
      colnames(corr_mat)
    )

    if (triangle == "upper") {

      corr_df <- corr_df[
        corr_df$row_id > corr_df$col_id,
      ]

    } else {

      corr_df <- corr_df[
        corr_df$row_id < corr_df$col_id,
      ]
    }
  }

  # -------------------------
  # 12. Drop unused factor levels
  # -------------------------
  corr_df$feature1 <- factor(
    corr_df$feature1,
    levels = rownames(corr_mat)
  )

  corr_df$feature2 <- factor(
    corr_df$feature2,
    levels = colnames(corr_mat)
  )

  corr_df <- droplevels(corr_df)

  # -------------------------
  # 13. Visual significance
  # -------------------------
  corr_df$signif <- ifelse(
    corr_df$pval < 0.001, "***",
    ifelse(
      corr_df$pval < 0.01, "**",
      ifelse(
        corr_df$pval < 0.05,
        "*",
        ""
      )
    )
  )

  # -------------------------
  # 14. Plot
  # -------------------------
  p <- NULL

  if (plot) {

    if (!requireNamespace("ggplot2", quietly = TRUE)) {
      stop("Please install 'ggplot2'")
    }

    p <- ggplot2::ggplot(
      corr_df,
      ggplot2::aes(
        x = .data$feature1,
        y = .data$feature2,
        fill = .data$cor
      )
    ) +

      ggplot2::coord_fixed() +

      ggplot2::geom_tile(
        color = "grey85",
        linewidth = 0.3
      ) +

      ggplot2::scale_y_discrete(
        limits = rev(levels(corr_df$feature2))
      ) +

      ggplot2::scale_fill_gradient2(
        low = "#2166ac",
        mid = "white",
        high = "#b2182b",
        midpoint = 0,
        limits = c(-1, 1)
      ) +

      ggplot2::theme_minimal(base_size = 12) +

      ggplot2::theme(
        axis.text.x = ggplot2::element_text(
          angle = 45,
          hjust = 1
        ),
        panel.grid = ggplot2::element_blank(),
        panel.background = ggplot2::element_blank(),
        axis.ticks = ggplot2::element_blank()
      ) +

      ggplot2::labs(
        title = paste("Correlation matrix - ", group),
        x = NULL,
        y = NULL,
        fill = "Correlation"
      )

    # -------------------------
    # 15. Significance overlay
    # -------------------------
    if (show_significance) {

      p <- p +

        ggplot2::geom_text(
          ggplot2::aes(label = signif),
          size = 4,
          color = "black"
        )
    }

    print(p)
  }

  # -------------------------
  # 16. Output
  # -------------------------
  obj <- list(association_matrix = corr_mat,
              feature_matrix = mat,
              annotation = annotation,
              method = method,
              genes = genes,
              group = group
  )

  class(obj) <- "cellsamble_association"

  # -------------------------
  # 14. Console summary
  # -------------------------
  .print_header("Cellsemble Association")

  .print_block("Summary", function() {

    cat("Method:             ", method, "\n")
    cat("Gene sets:          ", length(signatures), "\n")
    cat("Additional genes:   ", length(genes), "\n")
    cat("Total features:     ", ncol(mat), "\n")
    cat("Samples:            ", nrow(mat), "\n")
    cat("Group:              ", group, "\n")

  })

  # -------------------------
  # 15. Return
  # -------------------------
  return(invisible(obj))
}
