#' Estimate cell-type composition using EPIC
#'
#' Performs cell-type deconvolution using the EPIC algorithm through the
#' \pkg{immunedeconv} interface. Gene identifiers are automatically aligned,
#' converted to gene symbols, duplicated symbols are aggregated, and the
#' resulting cell-type scores are returned as a standardized
#' \code{cellsemble_result} object that can be used in downstream analyses such
#' as group comparisons and visualization.
#'
#' @param project A \code{rna_project} object generated by
#'   \code{autornaR}, containing expression data, sample metadata and gene
#'   annotation.
#' @param id Optional dataset identifier. Required only when \code{project}
#'   contains multiple datasets.
#' @param group_col Character string indicating the metadata column containing
#'   biological groups. This information is retained in the output object for
#'   downstream analyses.
#' @param min_score Minimum average EPIC score required for a cell signature to
#'   be retained. Signatures with lower mean abundance are removed from the
#'   output.
#' @param store_matrix Logical. If \code{TRUE}, the processed expression matrix
#'   is stored inside the returned object. Keeping it may facilitate downstream
#'   analyses but increases object size.
#' @param verbose Logical. If \code{TRUE}, prints a summary of the analysis and
#'   the most abundant inferred cell types.
#'
#' @return
#' An object of class \code{cellsemble_result} containing:
#' \itemize{
#'   \item Cell-type abundance scores for each sample.
#'   \item Metadata merged with the inferred scores.
#'   \item Cell signature annotations.
#'   \item Analysis parameters and summary information.
#'   \item Optionally, the processed expression matrix.
#' }
#'
#' @details
#' Expression data are automatically converted to gene symbols prior to
#' deconvolution. When multiple genes map to the same gene symbol, their
#' expression values are aggregated by summation. Cell-type deconvolution is
#' performed using the EPIC method implemented in the
#' \pkg{immunedeconv} package.
#'
#' @seealso
#' \code{\link{cellsemble_mcp_run}},
#' \code{\link{cellsemble_xcell_run}},
#' \code{\link{cellsemble_custom_run}},
#' \code{\link{cellsemble_compare}}
#'
#' @export

cellsemble_epic_run <- function(
    project,
    id = NULL,
    group_col = "Group",
    min_score = 0,
    store_matrix = FALSE,
    verbose = TRUE
) {

  # -------------------------
  # 0. Dependencies
  # -------------------------
  # Immunedecomv
  .cs_check_dependencies(
    c("immunedeconv"),
    source = "github"
  )

  # Epic
  .cs_check_dependencies(
    "EPIC",
    source = "bioc"
  )

  .cs_attach_if_needed("EPIC")

  # -------------------------
  # 1. Get data
  # -------------------------
  expr_matrix <- .cs_get_expr(project, id)
  metadata    <- .cs_get_meta(project, id)
  gene_annot  <- .cs_get_gene_annot(project, id)

  if (is.null(expr_matrix)) {
    stop("Expression matrix not found.")
  }

  expr_matrix <- as.matrix(expr_matrix)

  # -------------------------
  # 2. Align annotation
  # -------------------------
  gene_annot <- .cs_align_gene_annot(
    gene_annot,
    expr_matrix
  )

  valid <- !is.na(gene_annot$symbol)

  expr_matrix <- expr_matrix[
    valid,
    ,
    drop = FALSE
  ]

  gene_annot <- gene_annot[
    valid,
    ,
    drop = FALSE
  ]

  # -------------------------
  # 3. Convert ENSG -> SYMBOL
  # -------------------------
  rownames(expr_matrix) <- gene_annot$symbol

  # aggregate duplicated symbols
  expr_matrix <- rowsum(
    expr_matrix,
    group = rownames(expr_matrix)
  )

  # -------------------------
  # 4. Run EPIC
  # -------------------------
  epic_scores <- immunedeconv::deconvolute(
    expr_matrix,
    method = "epic"
  )

  # -------------------------
  # 5. Format output
  # -------------------------
  epic_scores <- as.data.frame(epic_scores)

  rownames(epic_scores) <- epic_scores$cell_type

  epic_scores$cell_type <- NULL

  epic_scores <- t(as.matrix(epic_scores))

  epic_scores <- as.data.frame(epic_scores)

  epic_scores$sample <- rownames(epic_scores)

  rownames(epic_scores) <- NULL

  # -------------------------
  # 6. Remove low-information signatures
  # -------------------------
  keep <- colMeans(
    epic_scores[
      ,
      !colnames(epic_scores) %in% "sample",
      drop = FALSE
    ]
  ) > min_score

  keep_names <- names(keep)[keep]

  scores <- epic_scores[
    ,
    c("sample", keep_names),
    drop = FALSE
  ]

  # -------------------------
  # 7. Merge metadata
  # -------------------------
  if (!is.null(metadata)) {

    if (!"Sample" %in% colnames(metadata)) {
      stop("Metadata must contain 'Sample' column")
    }

    metadata$sample <- as.character(metadata$Sample)

    scores <- merge(
      scores,
      metadata,
      by = "sample"
    )
  }

  # -------------------------
  # 8. Build gene sets structure
  # -------------------------
  signatures <- stats::setNames(
    lapply(keep_names, function(x) x),
    keep_names
  )

  annotation <- data.frame(
    feature = keep_names,
    type = "epic"
  )

  # -------------------------
  # 9. Output object
  # -------------------------
  obj <- list(
    scores = scores,
    signatures = signatures,
    annotation = annotation,
    coverage = NULL,
    expr_matrix = expr_matrix,
    aggregated_matrix = expr_matrix,
    score_matrix = expr_matrix,
    method = "epic",
    params = list(
      min_score = min_score
    ),
    dimensions = list(
      n_samples = ncol(expr_matrix),
      n_signatures = length(keep_names)
    ),
    source = "immunedeconv"
  )

  # -------------------------
  # 10. Optional matrix storage
  # -------------------------
  if (!store_matrix) {

    obj$expr_matrix <- NULL
    obj$aggregated_matrix <- NULL
    obj$score_matrix <- NULL
  }

  class(obj) <- "cellsemble_result"

  # -------------------------
  # 11. Console summary
  # -------------------------
  if (verbose) {

    .print_header("Cellsemble EPIC Run")

    .print_block("Summary", function() {

      cat("Samples:            ", nrow(scores), "\n")
      cat("EPIC signatures:    ", length(keep_names), "\n")
      cat("Minimum score:      ", min_score, "\n")
      cat("Matrix stored:      ", store_matrix, "\n")

    })

    .print_block("Top detected signatures", function() {

      avg_scores <- sort(
        colMeans(
          scores[
            ,
            keep_names,
            drop = FALSE
          ]
        ),
        decreasing = TRUE
      )

      print(
        round(
          utils::head(avg_scores, 10),
          3
        )
      )

    })
  }

  # -------------------------
  # 12. Return
  # -------------------------
  return(invisible(obj))
}
