#' Estimate cell-type enrichment using xCell
#'
#' Performs cell-type enrichment analysis using the xCell algorithm through the
#' \pkg{immunedeconv} interface. Gene identifiers are automatically aligned,
#' converted to gene symbols, duplicated symbols are aggregated, and the
#' resulting enrichment scores are returned as a standardized
#' \code{cellsemble_result} object that can be used in downstream analyses such
#' as group comparisons and visualization.
#'
#' @param project A \code{rna_project} object generated by
#'   \code{autornaR}, containing expression data, sample metadata and gene
#'   annotation.
#' @param id Optional dataset identifier. Required only when \code{project}
#'   contains multiple datasets.
#' @param group_col Character string indicating the metadata column containing
#'   biological groups. This information is retained in the output object for
#'   downstream analyses.
#' @param min_score Minimum average xCell enrichment score required for a cell
#'   signature to be retained. Signatures with lower mean enrichment scores are
#'   removed from the output.
#' @param store_matrix Logical. If \code{TRUE}, the processed expression matrix
#'   is stored inside the returned object. Keeping it may facilitate downstream
#'   analyses but increases object size.
#' @param verbose Logical. If \code{TRUE}, prints a summary of the analysis and
#'   the highest-scoring inferred cell signatures.
#'
#' @return
#' An object of class \code{cellsemble_result} containing:
#' \itemize{
#'   \item Cell-type enrichment scores for each sample.
#'   \item Metadata merged with the inferred scores.
#'   \item Cell signature annotations.
#'   \item Analysis parameters and summary information.
#'   \item Optionally, the processed expression matrix.
#' }
#'
#' @details
#' Expression data are automatically converted to gene symbols prior to
#' analysis. When multiple genes map to the same gene symbol, their expression
#' values are aggregated by summation. Cell-type enrichment scores are computed
#' using the xCell algorithm implemented through the
#' \pkg{immunedeconv} package. Cell signatures with mean enrichment scores below
#' \code{min_score} are excluded from the returned object.
#'
#' Unlike deconvolution methods that estimate cell-type proportions or
#' abundance, xCell computes relative enrichment scores based on gene
#' signatures. Therefore, xCell scores should be interpreted as relative
#' enrichment rather than absolute cell fractions.
#'
#' @seealso
#' \code{\link{cellsemble_epic_run}},
#' \code{\link{cellsemble_mcp_run}},
#' \code{\link{cellsemble_custom_run}},
#' \code{\link{cellsemble_compare}}
#'
#' @export

cellsemble_xcell_run <- function(
    project,
    id = NULL,
    group_col = "Group",
    min_score = 0,
    store_matrix = FALSE,
    verbose = TRUE
) {

  # -------------------------
  # 0. Dependencies
  # -------------------------
  if (!requireNamespace("immunedeconv", quietly = TRUE)) {
    stop(
      "Please install 'immunedeconv'\n",
      "install.packages('immunedeconv')"
    )
  }

  # -------------------------
  # 1. Get data
  # -------------------------
  expr_matrix <- .cs_get_expr(project, id)
  metadata    <- .cs_get_meta(project, id)
  gene_annot  <- .cs_get_gene_annot(project, id)

  if (is.null(expr_matrix)) {
    stop("Expression matrix not found.")
  }

  expr_matrix <- as.matrix(expr_matrix)

  # -------------------------
  # 2. Align annotation
  # -------------------------
  gene_annot <- .cs_align_gene_annot(
    gene_annot,
    expr_matrix
  )

  valid <- !is.na(gene_annot$symbol)

  expr_matrix <- expr_matrix[
    valid,
    ,
    drop = FALSE
  ]

  gene_annot <- gene_annot[
    valid,
    ,
    drop = FALSE
  ]

  # -------------------------
  # 3. Convert ENSG -> SYMBOL
  # -------------------------
  rownames(expr_matrix) <- gene_annot$symbol

  # aggregate duplicated symbols
  expr_matrix <- rowsum(
    expr_matrix,
    group = rownames(expr_matrix)
  )

  expr_matrix <- as.matrix(expr_matrix)
  storage.mode(expr_matrix) <- "double"

  # -------------------------
  # 4. Run xCell
  # -------------------------
  if (!requireNamespace("xCell", quietly = TRUE)) {
    stop(
      "Please install 'xCell'\n",
      "remotes::install_github('dviraran/xCell')"
    )
  }

  xcell_scores <- immunedeconv::deconvolute(
    expr_matrix,
    method = "xcell"
  )

  # -------------------------
  # 5. Format output
  # -------------------------
  xcell_scores <- as.data.frame(xcell_scores)

  rownames(xcell_scores) <- xcell_scores$cell_type

  xcell_scores$cell_type <- NULL

  xcell_scores <- t(as.matrix(xcell_scores))

  xcell_scores <- as.data.frame(xcell_scores)

  xcell_scores$sample <- rownames(xcell_scores)

  rownames(xcell_scores) <- NULL

  # -------------------------
  # 6. Remove low-information signatures
  # -------------------------
  keep <- colMeans(
    xcell_scores[
      ,
      !colnames(xcell_scores) %in% "sample",
      drop = FALSE
    ]
  ) > min_score

  keep_names <- names(keep)[keep]

  scores <- xcell_scores[
    ,
    c("sample", keep_names),
    drop = FALSE
  ]

  # -------------------------
  # 7. Merge metadata
  # -------------------------
  if (!is.null(metadata)) {

    if (!"Sample" %in% colnames(metadata)) {
      stop("Metadata must contain 'Sample' column")
    }

    metadata$sample <- as.character(metadata$Sample)

    scores <- merge(
      scores,
      metadata,
      by = "sample"
    )
  }

  # -------------------------
  # 8. Build gene sets structure
  # -------------------------
  signatures <- stats::setNames(
    lapply(keep_names, function(x) x),
    keep_names
  )

  annotation <- data.frame(
    feature = keep_names,
    type = "xcell"
  )

  # -------------------------
  # 9. Output object
  # -------------------------
  obj <- list(
    scores = scores,
    signatures = signatures,
    annotation = annotation,
    coverage = NULL,
    expr_matrix = expr_matrix,
    aggregated_matrix = expr_matrix,
    score_matrix = expr_matrix,
    method = "xcell",
    params = list(
      min_score = min_score
    ),
    dimensions = list(
      n_samples = ncol(expr_matrix),
      n_signatures = length(keep_names)
    ),
    source = "immunedeconv"
  )

  # -------------------------
  # 10. Optional matrix storage
  # -------------------------
  if (store_matrix) {

    obj$expr_matrix <- expr_matrix
  }

  class(obj) <- "cellsemble_result"

  # -------------------------
  # 11. Console summary
  # -------------------------
  if (verbose) {

    .print_header("Cellsemble xCell Run")

    .print_block("Summary", function() {

      cat("Samples:            ", nrow(scores), "\n")
      cat("xCell signatures:   ", length(keep_names), "\n")
      cat("Minimum score:      ", min_score, "\n")
      cat("Matrix stored:      ", store_matrix, "\n")

    })

    .print_block("Top detected signatures", function() {

      avg_scores <- sort(
        colMeans(
          scores[
            ,
            keep_names,
            drop = FALSE
          ]
        ),
        decreasing = TRUE
      )

      print(
        round(
          utils::head(avg_scores, 10),
          3
        )
      )

    })
  }

  # -------------------------
  # 12. Return
  # -------------------------
  return(invisible(obj))
}
