#' Score custom gene signatures from bulk transcriptomic data
#'
#' Computes sample-level scores for user-defined gene signatures by averaging
#' gene expression across each signature. Gene identifiers are automatically
#' aligned and converted to gene symbols, duplicated symbols are aggregated,
#' and optional gene-wise Z-score normalization can be applied prior to
#' scoring. The resulting signature scores are returned as a standardized
#' \code{cellsemble_result} object that can be used in downstream analyses such
#' as group comparisons and visualization.
#'
#' This function enables users to score custom biological programs,
#' cell states, or literature-derived signatures within the Cellsemble workflow.
#'
#' @param project A \code{rna_project} object generated by
#'   \code{autornaR}, containing expression data, sample metadata and gene
#'   annotation.
#' @param signatures A named list of gene signatures. Each element should be a
#'   character vector containing HGNC gene symbols.
#' @param parent_sets A named list defining parent-child relationships between signatures.
#'   The list name must correspond to the child signature, while the value
#'   specifies the parent signature. Used only when \code{adjustment = "subtract"}.
#'   For example, \code{list(myCAF = "Fibroblasts")} subtracts the parent
#'   signature score from the child signature score.
#' @param adjustment Character string specifying whether parent signature
#'   adjustment should be performed. Options are \code{"none"} (default) or
#'   \code{"subtract"}.
#' @param id Optional dataset identifier. Required only when
#'   \code{project} contains multiple datasets.
#' @param zscore Logical. If \code{TRUE}, gene-wise Z-score normalization is
#'   applied before signature scoring.
#' @param store_matrix Logical. If \code{TRUE}, processed expression matrices
#'   are stored inside the returned object. Keeping them may facilitate
#'   downstream analyses but increases object size.
#' @param verbose Logical. If \code{TRUE}, prints a summary of the analysis and
#'   gene set coverage statistics.
#'
#' @return
#' An object of class \code{cellsemble_result} containing:
#' \itemize{
#'   \item Sample-level signature scores.
#'   \item Gene set coverage statistics.
#'   \item Gene signature definitions.
#'   \item Analysis parameters and summary information.
#'   \item Optionally, the processed expression matrices.
#' }
#'
#' @details
#' Gene identifiers are automatically converted to HGNC gene symbols prior to
#' scoring. When multiple genes map to the same gene symbol, their expression
#' values are aggregated by summation. Signature scores are calculated as the
#' mean expression of all detected genes within each gene set.
#'
#' If \code{zscore = TRUE}, gene-wise Z-score normalization is applied before
#' score calculation, making signatures comparable across genes with different
#' expression ranges.
#'
#' Parent-child adjustment provides a simple strategy for estimating
#' conditional signatures. When \code{adjustment = "subtract"}, the score of
#' the specified parent signature is subtracted from its corresponding child
#' signature, allowing more specific biological programs to be evaluated after
#' accounting for broader cellular signatures.
#'
#' @examples
#' \dontrun{
#'
#' # Example 1: score two independent gene signatures
#'
#' signatures <- list(
#'
#' T_cells = c(
#'   "CD3D",
#'   "CD3E",
#'   "TRBC1"
#' ),
#'
#' B_cells = c(
#'   "MS4A1",
#'   "CD79A",
#'   "CD79B"
#'    )
#' )
#'
#' res <- cellsemble_custom_run(
#' project = proj,
#' signatures = signatures
#' )
#'
#'
#' # Example 2: estimate a conditional T cell signature after
#' accounting for the lymphocyte program
#'
#' signatures <- list(
#'
#'   Lymphocytes = c(
#'     "CD3D",
#'     "CD3E",
#'     "CD79A",
#'     "MS4A1"
#'   ),
#'
#'   T_cells = c(
#'     "CD3D",
#'     "CD3E",
#'     "TRBC1"
#'   )
#' )
#'
#' parent_sets <- list(
#'   T_cells = "Lymphocytes"
#' )
#'
#' res <- cellsemble_custom_run(
#'   project = proj,
#'   signatures = signatures,
#'   parent_sets = parent_sets,
#'   adjustment = "subtract"
#' )
#'}
#'
#' @seealso
#' \code{\link{cellsemble_compare}},
#' \code{\link{cellsemble_boxplot}},
#' \code{\link{cellsemble_epic_run}},
#' \code{\link{cellsemble_mcp_run}},
#' \code{\link{cellsemble_xcell_run}}
#'
#' @export

cellsemble_custom_run <- function(project,
                                  signatures,
                                  parent_sets = NULL,
                                  adjustment = c("none", "subtract"),
                                  id = NULL,
                                  zscore = TRUE,
                                  store_matrix = FALSE,
                                  verbose = TRUE) {

  adjustment <- match.arg(adjustment)

  # -------------------------
  # 1. Get data
  # -------------------------
  expr_matrix <- .cs_get_expr(project, id)
  metadata    <- .cs_get_meta(project, id)
  gene_annot  <- .cs_get_gene_annot(project, id)

  if (is.null(expr_matrix)) stop("Expression matrix not found.")

  expr_matrix <- as.matrix(expr_matrix)
  raw_matrix  <- expr_matrix

  # -------------------------
  # 2. Align genes
  # -------------------------
  gene_annot <- .cs_align_gene_annot(gene_annot, expr_matrix)

  valid <- !is.na(gene_annot$symbol)

  expr_matrix <- expr_matrix[valid, , drop = FALSE]
  gene_annot  <- gene_annot[valid, , drop = FALSE]

  rownames(expr_matrix) <- gene_annot$symbol

  expr_matrix <- rowsum(expr_matrix, group = rownames(expr_matrix))
  aggregated_matrix <- expr_matrix

  # HARD SAFETY CHECK
  if (is.null(colnames(expr_matrix)) || length(colnames(expr_matrix)) == 0) {
    colnames(expr_matrix) <- colnames(raw_matrix)
  }

  # -------------------------
  # 3. Z-score
  # -------------------------
  if (zscore) {

    expr_matrix <- t(scale(t(expr_matrix)))
    expr_matrix[is.na(expr_matrix)] <- 0

    colnames(expr_matrix) <- colnames(raw_matrix)
    rownames(expr_matrix) <- rownames(aggregated_matrix)
  }

  # -------------------------
  # 4. Scores
  # -------------------------
  if (!is.list(signatures) || is.null(names(signatures))) {
    stop("signatures must be a named list")
  }

  scores <- data.frame(sample = colnames(expr_matrix))

  for (gs_name in names(signatures)) {

    genes <- signatures[[gs_name]]
    common <- intersect(genes, rownames(expr_matrix))

    if (length(common) == 0) {
      scores[[gs_name]] <- rep(NA, ncol(expr_matrix))
    } else {
      scores[[gs_name]] <- colMeans(expr_matrix[common, , drop = FALSE])
    }
  }

  # Coverage
  coverage <- .check_gene_set_coverage(expr_matrix, signatures)

  # -------------------------
  # 5. Parent adjustment
  # -------------------------
  if (adjustment == "subtract") {

    if (is.null(parent_sets)) {
      stop("parent_sets required for subtraction")
    }

    if (!is.list(parent_sets) || is.null(names(parent_sets))) {
      stop("parent_sets must be a named list: list(child = 'parent')")
    }

    for (child in names(parent_sets)) {

      parent <- parent_sets[[child]]

      if (!child %in% colnames(scores)) {
        warning(paste("Missing child:", child))
        next
      }

      if (!parent %in% colnames(scores)) {
        warning(paste("Missing parent:", parent))
        next
      }

      # conditional signature scoring
      scores[[child]] <- scores[[child]] - scores[[parent]]
    }
  }

  # -------------------------
  # 6. Metadata (aligned only)
  # -------------------------
  metadata$sample <- as.character(metadata$Sample)

  idx <- match(scores$sample, metadata$sample)
  metadata_aligned <- metadata[idx, , drop = FALSE]

  if (!"Group" %in% colnames(metadata_aligned)) {
    stop("Group column not found in metadata")
  }

  scores$Group <- metadata_aligned$Group

  # -------------------------
  # 7. Output
  # -------------------------
  obj <- list(

    # core results
    scores = scores,
    coverage = coverage,

    # input structure (optional storage)
    data = list(
      expr_matrix = if (store_matrix) raw_matrix else NULL,
      aggregated_matrix = if (store_matrix) aggregated_matrix else NULL
    ),

    # model configuration
    signatures = signatures,
    method = "custom_signature",
    params = list(zscore = zscore),

    # metadata
    metadata = metadata,

    # summary
    dimensions = list(
      n_genes = nrow(expr_matrix),
      n_samples = ncol(expr_matrix)
    )
  )

  class(obj) <- "cellsemble_result"

  # -------------------------
  # 8. Console summary
  # -------------------------
  if (verbose) {

  .print_header("Cellsemble Run")

  .print_block("Dataset summary", function() {

    cat("Samples:          ", ncol(expr_matrix), "\n")
    cat("Genes:            ", nrow(expr_matrix), "\n")
    cat("Gene sets:        ", length(signatures), "\n")
    cat("Scoring method:   ", "custom_signature", "\n")
    cat("Z-score applied:  ", zscore, "\n")

  })

  .print_block("Gene set coverage", function() {

    cov <- data.frame(
      gene_set = names(coverage),
      detected = sapply(coverage, function(x) x$detected),
      total = sapply(coverage, function(x) x$total),
      coverage = round(
        sapply(coverage, function(x) x$proportion),
        2
      )
    )

    print(cov)

  })
}

  # -------------------------
  # 9. Return
  # -------------------------
  return(invisible(obj))
}
