#' Visualize cell signature profiles using heatmaps
#'
#' Generates heatmaps from sample-level cell signature scores stored in a
#' \code{cellsemble_result} object. The function supports visualization of
#' individual sample profiles or aggregated group-level patterns, allowing
#' exploration of cellular composition and biological programs across
#' experimental conditions.
#'
#' @param x A \code{cellsemble_result} object generated by
#'   \code{cellsemble_*_run()} functions, containing sample-level signature
#'   scores.
#' @param group_col Character string specifying the metadata column containing
#'   sample groups. Used for row annotations and group aggregation.
#'   Default is \code{"Group"}.
#' @param mode Visualization mode. \code{"standard"} displays individual
#'   samples, while \code{"aggregate"} summarizes signature scores by group.
#' @param scale Logical. If \code{TRUE}, signature scores are standardized
#'   across features before visualization.
#' @param cluster_rows Logical. If \code{TRUE}, hierarchical clustering is
#'   applied to rows.
#' @param cluster_cols Logical. If \code{TRUE}, hierarchical clustering is
#'   applied to columns.
#' @param show_rownames Logical. Whether sample names should be displayed.
#' @param show_colnames Logical. Whether signature names should be displayed.
#'
#' @return
#' An object of class \code{cellsemble_heatmap} containing:
#' \itemize{
#'   \item The matrix used for visualization.
#'   \item Row annotation information when available.
#'   \item Heatmap parameters.
#'   \item The generated \code{ComplexHeatmap} object.
#' }
#'
#' @details
#' The heatmap is generated from signature scores rather than raw expression
#' values. Therefore, patterns represent differences in inferred cellular
#' signatures or biological programs between samples.
#'
#' In \code{mode = "standard"}, each row corresponds to an individual sample,
#' enabling visualization of sample heterogeneity. When \code{group_col} is
#' provided, samples are annotated according to their experimental groups.
#'
#' In \code{mode = "aggregate"}, samples are summarized by calculating the
#' mean signature score within each group. This mode is useful for obtaining
#' an overview of global differences between experimental conditions.
#'
#' When \code{scale = TRUE}, each signature is standardized before plotting,
#' emphasizing relative enrichment patterns rather than absolute score
#' magnitude.
#'
#' Hierarchical clustering is performed on the displayed matrix and can be
#' independently controlled for rows and columns.
#'
#' @examples
#' \dontrun{
#'
#' # Heatmap showing individual samples
#' res_heat <- cellsemble_heatmap(
#'   x = res
#' )
#'
#' # Heatmap aggregated by experimental group
#' res_heat_group <- cellsemble_heatmap(
#'   x = res,
#'   mode = "aggregate",
#'   group_col = "Group"
#' )
#'}
#'
#' @seealso
#' \code{\link{cellsemble_dimred}},
#' \code{\link{cellsemble_boxplot}},
#' \code{\link{cellsemble_delta}},
#' \code{\link{cellsemble_compare}}
#'
#' @export

cellsemble_heatmap <- function(
    x,
    group_col = "Group",
    mode = c("standard", "aggregate"),
    scale = TRUE,
    cluster_rows = TRUE,
    cluster_cols = TRUE,
    show_rownames = TRUE,
    show_colnames = TRUE
) {

  mode <- match.arg(mode)

  # -------------------------
  # 1. Get data
  # -------------------------
  df <- x$scores
  signatures <- names(x$signatures)

  # -------------------------
  # 2. Validate input
  # -------------------------
  if (!inherits(x, "cellsemble_result")) {
    stop(
      "Input must be a 'cellsemble_result'. Run cellsemble_run() first."
    )
  }

  if (length(signatures) == 0) {
    stop("No gene sets found in object.")
  }

  if (!is.null(group_col) &&
      !group_col %in% colnames(df)) {

    stop("group_col not found in scores data")
  }

  # -------------------------
  # 3. Build matrix
  # -------------------------
  mat_df <- df[, signatures, drop = FALSE]
  mat_df[] <- lapply(mat_df, as.numeric)

  mat <- as.matrix(mat_df)

  rownames(mat) <- df$sample

  # -------------------------
  # 4. Aggregate by group
  # -------------------------
  if (mode == "aggregate") {

    if (is.null(group_col)) {
      stop(
        "aggregate mode requires group_col"
      )
    }

    group_vec <- df[[group_col]]
    names(group_vec) <- df$sample
    group_vec <- group_vec[
      rownames(mat)
    ]

    ok <- !is.na(group_vec)
    mat <- mat[
      ok,
      ,
      drop = FALSE
    ]

    group_vec <- group_vec[ok]

    mat <- t(

      apply(
        mat,
        2,

        function(col) {

          tapply(
            col,
            group_vec,
            mean,
            na.rm = TRUE
          )
        }
      )
    )

    mat <- as.matrix(mat)

  }

  # -------------------------
  # 5. Scaling
  # -------------------------
  if (scale) {

    sds <- apply(
      mat,
      2,
      stats::sd,
      na.rm = TRUE
    )

    mat <- mat[
      ,
      sds > 0 & !is.na(sds),
      drop = FALSE
    ]

    if (nrow(mat) > 1) {

      mat <- scale(mat)

    }

  }

  # -------------------------
  # 6. Annotation
  # -------------------------
  base_fontsize <- 10

  row_names_gp <- grid::gpar(
    fontsize = base_fontsize
  )

  column_names_gp <- grid::gpar(
    fontsize = base_fontsize
  )

  legend_gp <- grid::gpar(
    fontsize = base_fontsize
  )

  ha <- NULL

  if (
    mode == "standard" &&
    !is.null(group_col)
  ) {

    if (!requireNamespace(
      "ComplexHeatmap",
      quietly = TRUE
    )) {

      stop(
        "Please install ComplexHeatmap"
      )

    }

    if (!requireNamespace(
      "circlize",
      quietly = TRUE
    )) {

      stop(
        "Please install circlize"
      )

    }

    group_vec <- df[[group_col]]
    names(group_vec) <- df$sample
    group_vec <- group_vec[
      rownames(mat)
    ]

    groups <- unique(group_vec)

    custom_cols <- c(
      "#66C2A5",
      "#8DA0CB",
      "#FC8D62",
      "#E78AC3",
      "#A6D854"
    )

    palette <- stats::setNames(

      rep(
        custom_cols,
        length.out = length(groups)
      ),

      groups

    )

    ha <- ComplexHeatmap::rowAnnotation(
      Group = group_vec,
      col = list(
        Group = palette
      ),

      annotation_name_rot = 45,
      annotation_name_gp =
        grid::gpar(
          fontsize = base_fontsize
        ),

      show_annotation_name = TRUE

    )

  }

  # -------------------------
  # 7. Heatmap
  # -------------------------
  if (!requireNamespace(
    "ComplexHeatmap",
    quietly = TRUE
  )) {

    stop(
      "Please install ComplexHeatmap"
    )

  }

  if (!requireNamespace(
    "circlize",
    quietly = TRUE
  )) {

    stop(
      "Please install circlize"
    )

  }

  mat_min <- min(
    mat,
    na.rm = TRUE
  )

  mat_max <- max(
    mat,
    na.rm = TRUE
  )

  ht <- ComplexHeatmap::Heatmap(
    mat,
    name = "Score",

    col = circlize::colorRamp2(

      c(mat_min, 0, mat_max),
      c("#2166ac", "white","#b2182b")
    ),

    left_annotation = ha,

    cluster_rows = cluster_rows,
    cluster_columns = cluster_cols,

    show_row_names = show_rownames,
    show_column_names = show_colnames,

    column_names_rot = 45,

    row_names_gp = row_names_gp,
    column_names_gp = column_names_gp,

    heatmap_legend_param = list(
      title_gp = legend_gp,
      labels_gp = legend_gp
    )
  )

  ComplexHeatmap::draw(
    ht,
    heatmap_legend_side = "right"
  )

  # -------------------------
  # 8. Output
  # -------------------------
  out <- list(

    matrix = mat,

    annotation_row = if (
      mode == "standard" &&
      !is.null(group_col)
    ) group_vec else NULL,

    annotation_col = NULL,

    params = list(
      mode = mode,
      scale = scale,
      cluster_rows = cluster_rows,
      cluster_cols = cluster_cols

    ),

    heatmap = ht

  )

  class(out) <- "cellsemble_heatmap"

  invisible(out)

}
