#' Visualize differential changes in Cellsemble scores
#'
#' Generates a graphical summary of changes in biological signatures between
#' two groups based on results obtained from \code{\link{cellsemble_compare}}.
#' The function displays either raw score differences or standardized effect
#' sizes together with confidence intervals and statistical significance.
#'
#' @param compare_obj A \code{cellsemble_compare} object generated by
#'   \code{\link{cellsemble_compare}}.
#' @param metric Character string specifying the metric used to visualize
#'   group differences. Options are \code{"effect_size"} (default), which
#'   displays standardized differences between groups, or
#'   \code{"difference"}, which displays absolute differences in signature
#'   scores.
#' @param significance Logical. If \code{TRUE}, significance labels based on
#'   adjusted p-values are displayed on the plot.
#' @param alpha Numeric value defining the significance threshold used for
#'   significance labels. Default is \code{0.05}.
#' @param sort Logical. If \code{TRUE}, signatures are ordered according to
#'   the selected metric.
#'
#' @return
#' An object of class \code{cellsemble_delta} containing:
#' \itemize{
#'   \item The processed differential signature table.
#'   \item The selected visualization metric.
#'   \item The significance threshold.
#'   \item The generated ggplot object.
#' }
#'
#' @details
#' \code{cellsemble_delta} summarizes changes detected by
#' \code{\link{cellsemble_compare}}. Positive values indicate higher signature
#' scores in the second comparison group, while negative values indicate higher
#' scores in the first comparison group.
#'
#' When \code{metric = "difference"}, the displayed values correspond to the
#' difference between group means:
#'
#' \deqn{difference = mean(group2) - mean(group1)}
#'
#' When \code{metric = "effect_size"}, standardized effect sizes are displayed,
#' allowing comparison of changes across signatures with different score
#' distributions.
#'
#' Confidence intervals are displayed when available from bootstrap estimation
#' performed during \code{\link{cellsemble_compare}}. Significance labels
#' correspond to adjusted p-values after multiple testing correction.
#'
#' @examples
#' \dontrun{
#'
#' # Compare signatures between two groups
#'
#' comparison <- cellsemble_compare(
#'   comparison,
#'   group_col = "Group"
#' )
#'
#' # Visualize effect sizes
#'
#' delta <- cellsemble_delta(
#'   comparison,
#'   metric = "effect_size"
#' )
#'
#' # Visualize absolute score differences
#'
#' delta <- cellsemble_delta(
#'   comparison,
#'   metric = "difference"
#' )
#'}
#'
#' @seealso
#' \code{\link{cellsemble_compare}},
#' \code{\link{cellsemble_boxplot}},
#' \code{\link{cellsemble_association}}
#'
#' @export

cellsemble_delta <- function(compare_obj,
                             metric = c("effect_size", "difference"),
                             significance = TRUE,
                             alpha = 0.05,
                             sort = TRUE
) {

  metric <- match.arg(metric)

  # -------------------------
  # 1. Validation
  # -------------------------
  if (!inherits(compare_obj, "cellsemble_compare")) {

    stop(
      "Input must be a 'cellsemble_compare' object."
    )
  }

  df <- compare_obj$results

  if (metric == "difference") {

    df$ci_low  <- df$difference_ci_low
    df$ci_high <- df$difference_ci_high

  } else {

    df$ci_low  <- df$effect_ci_low
    df$ci_high <- df$effect_ci_high

  }

  if (all(is.na(df$ci_low))) {
    cat("Bootstrap CI:       Not available\n")
  } else {
    cat("Bootstrap CI:       Available\n")
  }

  # -------------------------
  # 2. Direction
  # -------------------------

  g1 <- unique(df$group1)
  g2 <- unique(df$group2)

  df$Direction <- ifelse(

    df[[metric]] > 0,

    paste0(
      "Higher in ",
      g2
    ),

    paste0(
      "Higher in ",
      g1
    )

  )

  # -------------------------
  # 3. Significance stars
  # -------------------------
  df$stars <- ifelse(
    df$p_adj < 0.001,
    "***",
    ifelse(
      df$p_adj < 0.01,
      "**",
      ifelse(
        df$p_adj < alpha,
        "*",
        ""
      )
    )
  )

  # -------------------------
  # 4. Sort and Factorize
  # -------------------------
  if (sort) {
    df <- df[
      order(df[[metric]]),
    ]
  }

  df$signatures <- factor(df$signatures, levels = unique(df$signatures))

  # -------------------------
  # 5. Star position
  # -------------------------
  rng <- diff(
    range(
      df[[metric]],
      na.rm = TRUE
    )
  )

  offset <- rng * 0.05

  df$label_y <- ifelse(
    df[[metric]] > 0,
    df$ci_high + offset,
    df$ci_low - offset
  )

  # -------------------------
  # 6. Plot
  # -------------------------
  p <- ggplot2::ggplot(
    df,
    ggplot2::aes(
      x = .data$signatures,
      y = .data[[metric]],
      fill = .data$Direction
    )
  ) +

    ggplot2::geom_col(
      width = 0.8
    ) +

    ggplot2::geom_errorbar(
      ggplot2::aes(
        ymin = .data$ci_low,
        ymax = .data$ci_high
      ),

      width = 0.15,
      linewidth = 0.5,
      colour = "grey20"
    ) +

    ggplot2::geom_point(
      shape = 21,
      fill = "grey20",
      colour = "grey20",
      size = 2
    ) +

    ggplot2::coord_flip() +

    ggplot2::geom_hline(
      yintercept = 0,
      linewidth = 0.5,
      colour = "grey80"
    ) +

    ggplot2::scale_fill_manual(
      values = c(
        "#2166ac",
        "#b2182b"
      )
    ) +

    ggplot2::labs(
      title = paste0(
        "Differential Cellsemble Scores"
      ),
      y = metric,
      x = NULL,
      fill = NULL
    ) +

    ggplot2::expand_limits(
      y = c(
        min(df$ci_low) - offset * 2,
        max(df$ci_high) + offset * 2
      )
    )

  p <- p +
    ggplot2::theme_minimal(
    base_size = 12
  ) +

    ggplot2::theme(

      panel.grid.major.y =
        ggplot2::element_blank(),

      panel.grid.minor =
        ggplot2::element_blank(),

      legend.position = "top",

      plot.title =
        ggplot2::element_text(
        )
    )

  # -------------------------
  # 7. Stars
  # -------------------------
  if (significance) {

    df_stars <- df[df$stars != "", , drop = FALSE]

    if (nrow(df_stars) > 0) {
      p <- p +
        ggplot2::geom_text(
          data = df_stars,

          ggplot2::aes(
            y = .data$label_y,
            label = .data$stars
          ),

          size = 4
        )
    }
  }

  print(p)

  # -------------------------
  # 8. Output
  # -------------------------
  out <- list(
    data = df,
    metric = metric,
    alpha = alpha,
    plot = p
  )

  class(out) <- "cellsemble_delta"

  # -------------------------
  # Console summary
  # -------------------------
  .print_header("Cellsemble Delta")

  .print_block("Summary", function() {

    cat("Metric:             ", metric, "\n")
    cat("Significance shown: ", significance, "\n")
    cat("Alpha threshold:    ", alpha, "\n")
    cat("Signatures tested:  ", nrow(df), "\n")

  })

  .print_block("Comparison", function() {

    cat(
      "Groups:             ",
      unique(df$group1),
      " vs ",
      unique(df$group2),
      "\n",
      sep = ""
    )

  })

  .print_block("Direction summary", function() {

    print(
      table(df$Direction)
    )

  })

  .print_block("Top changes", function() {

    top <- df[
      order(
        abs(df[[metric]]),
        decreasing = TRUE
      ),
    ]

    print(
      utils::head(
        top[
          ,
          c(
            "signatures",
            metric,
            "Direction",
            "p_adj"
          )
        ],
        5
      )
    )
  })

  invisible(out)

}
