#' Estimate cell-type abundance using MCP-counter
#'
#' Performs cell-type abundance estimation using the MCP-counter algorithm.
#' Gene identifiers are automatically aligned and converted to HGNC gene
#' symbols before abundance estimation. The resulting cell population scores
#' are returned as a standardized \code{cellsemble_result} object that can be
#' used in downstream analyses such as group comparisons and visualization.
#'
#' @param project A \code{rna_project} object generated by
#'   \code{autornaR}, containing expression data, sample metadata and gene
#'   annotation.
#' @param id Optional dataset identifier. Required only when \code{project}
#'   contains multiple datasets.
#' @param group_col Character string indicating the metadata column containing
#'   biological groups. This information is retained in the output object for
#'   downstream analyses.
#' @param min_score Minimum average MCP-counter score required for a cell
#'   population to be retained. Populations with lower mean abundance are
#'   removed from the output.
#' @param store_matrix Logical. If \code{TRUE}, the processed expression matrix
#'   is stored inside the returned object. Keeping it may facilitate downstream
#'   analyses but increases object size.
#' @param verbose Logical. If \code{TRUE}, prints a summary of the analysis and
#'   the most abundant inferred cell populations.
#'
#' @return
#' An object of class \code{cellsemble_result} containing:
#' \itemize{
#'   \item Cell population abundance scores for each sample.
#'   \item Metadata merged with the inferred scores.
#'   \item Cell population annotations.
#'   \item Analysis parameters and summary information.
#'   \item Optionally, the processed expression matrix.
#' }
#'
#' @details
#' Expression data are automatically processed and converted to HGNC gene
#' symbols before abundance estimation. Cell population scores are computed
#' using the MCP-counter algorithm implemented in the
#' \pkg{MCPcounter} package. Cell populations with mean scores below
#' \code{min_score} are excluded from the returned object.
#'
#' @seealso
#' \code{\link{cellsemble_epic_run}},
#' \code{\link{cellsemble_xcell_run}},
#' \code{\link{cellsemble_custom_run}},
#' \code{\link{cellsemble_compare}}
#'
#' @export

cellsemble_mcp_run <- function(
    project,
    id = NULL,
    group_col = "Group",
    min_score = 0,
    store_matrix = FALSE,
    verbose = TRUE
) {

  # -------------------------
  # 0. Dependencies
  # -------------------------
  .cs_check_dependencies(
    "MCPcounter",
    source = "bioc"
  )

  .cs_check_dependencies(
    "org.Hs.eg.db",
    source = "bioc"
  )

  stopifnot(requireNamespace("AnnotationDbi", quietly = TRUE))

  .cs_attach_if_needed("MCPcounter")

  # -------------------------
  # 1. Prepare expression (NEW LAYER)
  # -------------------------
  expr_matrix <- .cs_prepare_expression_for_method(
    project = project,
    id = id,
    method = "mcp_counter"
  )

  metadata <- .cs_get_meta(project, id)

  if (is.null(expr_matrix)) {
    stop("Expression matrix not found.")
  }

  # -------------------------
  # 2. Run MCP-counter
  # -------------------------
  mcp_scores <- MCPcounter::MCPcounter.estimate(
    expr_matrix,
    featuresType = "HUGO_symbols"
  )

  mcp_scores <- as.matrix(mcp_scores)

  # safety check (IMPORTANT)
  if (nrow(mcp_scores) == 0 || ncol(mcp_scores) == 0) {
    stop(
      "MCP-counter returned empty matrix after gene mapping. ",
      "Check gene symbol compatibility."
    )
  }

  # -------------------------
  # 3. Format output
  # -------------------------
  mcp_scores <- as.data.frame(t(mcp_scores))

  mcp_scores$sample <- rownames(mcp_scores)
  rownames(mcp_scores) <- NULL

  # -------------------------
  # 4. Remove low-information signatures
  # -------------------------
  score_cols <- setdiff(colnames(mcp_scores), "sample")

  keep <- colMeans(mcp_scores[, score_cols, drop = FALSE]) > min_score
  keep_names <- names(keep)[keep]

  if (length(keep_names) == 0) {
    stop("No MCP signatures passed min_score filter.")
  }

  scores <- mcp_scores[, c("sample", keep_names), drop = FALSE]

  # -------------------------
  # 5. Merge metadata
  # -------------------------
  if (!is.null(metadata)) {

    if (!"Sample" %in% colnames(metadata)) {
      stop("Metadata must contain 'Sample' column")
    }

    metadata$sample <- as.character(metadata$Sample)

    scores <- merge(scores, metadata, by = "sample")
  }

  # -------------------------
  # 6. Build gene sets structure
  # -------------------------
  signatures <- stats::setNames(
    lapply(keep_names, identity),
    keep_names
  )

  annotation <- data.frame(
    feature = keep_names,
    type = "mcp_counter"
  )

  # -------------------------
  # 7. Output object
  # -------------------------
  obj <- list(
    scores = scores,
    signatures = signatures,
    annotation = annotation,
    coverage = NULL,
    expr_matrix = expr_matrix,
    aggregated_matrix = expr_matrix,
    score_matrix = expr_matrix,
    method = "mcp_counter",
    params = list(
      min_score = min_score
    ),
    dimensions = list(
      n_samples = nrow(scores),
      n_signatures = length(keep_names)
    ),
    source = "mcpcounter"
  )

  # -------------------------
  # 8. Optional matrix storage
  # -------------------------
  if (!store_matrix) {
    obj$expr_matrix <- NULL
    obj$aggregated_matrix <- NULL
    obj$score_matrix <- NULL
  }

  class(obj) <- "cellsemble_result"

  # -------------------------
  # 9. Console summary
  # -------------------------
  if (verbose) {

    .print_header("Cellsemble MCP-counter Run")

    .print_block("Summary", function() {
      cat("Samples:           ", nrow(scores), "\n")
      cat("MCP signatures:    ", length(keep_names), "\n")
      cat("Min score:         ", min_score, "\n")
      cat("Matrix stored:     ", store_matrix, "\n")
    })

    .print_block("Top detected signatures", function() {

      avg_scores <- sort(
        colMeans(scores[, keep_names, drop = FALSE]),
        decreasing = TRUE
      )

      print(round(utils::head(avg_scores, 10), 3))
    })
  }

  # -------------------------
  # 10. Return
  # -------------------------
  return(invisible(obj))
}
