#' Compare cell signature scores between experimental groups
#'
#' Performs statistical comparisons of cell signature scores or custom
#' biological programs between two experimental groups. The function accepts
#' a \code{cellsemble_result} object generated by any Cellsemble scoring
#' method, including EPIC, MCP-counter, xCell, or custom signatures.
#'
#' For each signature, descriptive statistics, effect sizes, hypothesis tests,
#' confidence intervals and multiple-testing corrected p-values are calculated.
#' Statistical tests can be automatically selected based on normality and
#' variance assumptions or manually specified by the user.
#'
#' @param x An object of class \code{cellsemble_result} generated by a
#'   Cellsemble scoring function.
#' @param group_col Character string indicating the metadata column containing
#'   the groups to compare.
#' @param method Character string specifying the statistical test. Options are
#'   \code{"auto"} (default), \code{"t.test"}, \code{"welch"}, or
#'   \code{"wilcox"}.
#' @param ref_group Optional character string specifying the reference group.
#'   When provided, the comparison direction is set relative to this group.
#' @param bootstrap Logical. If \code{TRUE}, bootstrap confidence intervals for
#'   differences and effect sizes are estimated.
#' @param B Number of bootstrap iterations.
#' @param alpha Significance threshold used for assumption testing.
#'
#' @return
#' An object of class \code{cellsemble_compare} containing:
#' \itemize{
#'   \item Statistical results for each tested signature.
#'   \item Group means and effect sizes.
#'   \item Confidence intervals estimated by bootstrap.
#'   \item Raw and adjusted p-values.
#'   \item Information about the selected statistical methods.
#' }
#'
#' @details
#' The function currently supports comparisons between two groups. When
#' \code{method = "auto"}, normality and variance assumptions are evaluated
#' before selecting the statistical test:
#' \itemize{
#'   \item Wilcoxon rank-sum test when normality assumptions are not met.
#'   \item Welch's t-test when groups show unequal variances.
#'   \item Student's t-test when data are approximately normal with homogeneous
#'   variances.
#' }
#'
#' Effect sizes are calculated as standardized mean differences. Bootstrap
#' confidence intervals are generated independently for mean differences and
#' effect sizes. Multiple testing correction is performed using the
#' Benjamini-Hochberg procedure.
#'
#' @seealso
#' \code{\link{cellsemble_boxplot}},
#' \code{\link{cellsemble_custom_run}},
#' \code{\link{cellsemble_epic_run}},
#' \code{\link{cellsemble_mcp_run}},
#' \code{\link{cellsemble_xcell_run}}
#'
#' @export

cellsemble_compare <- function(
    x,
    group_col = "Group",
    method = c("auto", "t.test", "welch", "wilcox"),
    ref_group = NULL,
    bootstrap = TRUE,
    B = 5000,
    alpha = 0.05
) {

  method <- match.arg(method)

  # -------------------------
  # 1. Get data
  # -------------------------
  df <- x$scores
  signatures <- names(x$signatures)

  # -------------------------
  # 2. Validate input
  # -------------------------
  if (!inherits(x, "cellsemble_result")) {
    stop("Input must be a 'cellsemble_result'")
  }

  if (!group_col %in% colnames(df)) {
    stop("group_col not found in scores data")
  }

  if (length(signatures) == 0) {
    stop("No gene sets found")
  }

  # -------------------------
  # 3. Prepare groups
  # -------------------------
  df[[group_col]] <- as.factor(df[[group_col]])

  groups <- levels(df[[group_col]])

  if (length(groups) != 2) {
    stop("Currently supports only 2 groups.")
  }

  if (!is.null(ref_group)) {

    if (!ref_group %in% groups) {
      stop("ref_group not found.")
    }

    groups <- c(
      ref_group,
      setdiff(groups, ref_group)
    )
  }

  g1 <- groups[1]
  g2 <- groups[2]

  message("Comparing groups: ", g1, " vs ", g2)

  # -------------------------
  # 4. Compute statistics
  # -------------------------
  results <- list()

  for (gs in signatures) {

    # -------------------------
    # 4.1 Extract data
    # -------------------------
    x1 <- df[df[[group_col]] == g1, gs]
    x2 <- df[df[[group_col]] == g2, gs]

    x1 <- x1[!is.na(x1)]
    x2 <- x2[!is.na(x2)]

    # -------------------------
    # 4.2 Descriptive stats
    # -------------------------
    m1 <- mean(x1)
    m2 <- mean(x2)

    diff <- m2 - m1

    sd_pooled <- sqrt(
      (
        stats::var(x1) +
          stats::var(x2)
      ) / 2
    )

    effect_size <- diff / sd_pooled

    # -------------------------
    # 4.3 Assumption testing
    # -------------------------
    p_norm1 <- tryCatch(
      stats::shapiro.test(x1)$p.value,
      error = function(e) NA
    )

    p_norm2 <- tryCatch(
      stats::shapiro.test(x2)$p.value,
      error = function(e) NA
    )

    normal <- (
      p_norm1 > alpha &&
        p_norm2 > alpha
    )

    tmp_df <- data.frame(
      value = c(x1, x2),
      group = factor(c(
        rep(g1, length(x1)),
        rep(g2, length(x2))
      ))
    )

    p_var <- tryCatch({

      car::leveneTest(
        value ~ group,
        data = tmp_df
      )$`Pr(>F)`[1]

    }, error = function(e) {
      NA
    })

    homogeneous <- p_var > alpha

    # -------------------------
    # 4.4 Select method
    # -------------------------
    if (method == "auto") {

      selected_method <- if (!normal) {
        "wilcox"
      } else if (!homogeneous) {
        "welch"
      } else {
        "t.test"
      }

    } else {

      selected_method <- method
    }

    # -------------------------
    # 4.5 Statistical test
    # -------------------------
    test <- tryCatch({

      if (selected_method == "wilcox") {

        stats::wilcox.test(x1, x2)

      } else if (selected_method == "welch") {

        stats::t.test(
          x1,
          x2,
          var.equal = FALSE
        )

      } else {

        stats::t.test(
          x1,
          x2,
          var.equal = TRUE
        )
      }

    }, error = function(e) {
      NULL
    })

    pval <- if (!is.null(test)) {
      test$p.value
    } else {
      NA
    }

    # -------------------------
    # 4.6 Bootstrap CI
    # -------------------------

    difference_ci_low  <- NA
    difference_ci_high <- NA

    effect_ci_low      <- NA
    effect_ci_high     <- NA

    if (bootstrap) {

      # -------------------------
      # Difference CI
      # -------------------------

      boot_diff <- .boot_two_sample(
        x1,
        x2,

        stat_fun = function(a, b) {
          mean(b) - mean(a)
        },

        B = B
      )

      difference_ci_low  <- boot_diff$ci_low
      difference_ci_high <- boot_diff$ci_high

      # -------------------------
      # Effect size CI
      # -------------------------

      boot_effect <- .boot_two_sample(
        x1,
        x2,

        stat_fun = function(a, b) {
          diff <- mean(b) - mean(a)
          pooled_sd <- sqrt(
            (
              stats::var(a) +
                stats::var(b)
            ) / 2
          )

          if (
            is.na(pooled_sd) ||
            pooled_sd == 0
          ) {

            return(NA_real_)

          }

          diff / pooled_sd

        },

        B = B

      )

      effect_ci_low  <- boot_effect$ci_low
      effect_ci_high <- boot_effect$ci_high

    }

    # -------------------------
    # 4.7 Store results
    # -------------------------
    results[[gs]] <- data.frame(

      gene_set = gs,

      group1 = g1,
      group2 = g2,

      mean_group1 = m1,
      mean_group2 = m2,

      difference = diff,
      effect_size = effect_size,

      difference_ci_low  = difference_ci_low,
      difference_ci_high = difference_ci_high,

      effect_ci_low      = effect_ci_low,
      effect_ci_high     = effect_ci_high,

      p_norm_group1 = p_norm1,
      p_norm_group2 = p_norm2,
      p_variance = p_var,

      normal = normal,
      homogeneous = homogeneous,

      method = selected_method,

      p_value = pval
    )
  }

  # -------------------------
  # 5. Multiple testing correction
  # -------------------------
  out <- do.call(rbind, results)

  out$p_adj <- stats::p.adjust(
    out$p_value,
    method = "BH"
  )

  rownames(out) <- NULL

  # -------------------------
  # 6. Build output
  # -------------------------
  obj <- list(
    results = out,
    input_method = method,
    group_col = group_col,
    groups = groups,
    bootstrap = bootstrap,
    B = B
  )

  class(obj) <- "cellsemble_compare"

  # -------------------------
  # 7. Console summary
  # -------------------------
  .print_header("Cellsemble Comparison")

  .print_block("Summary", function() {

    cat("Input method:       ", method, "\n")
    cat("Groups compared:    ", g1, " vs ", g2, "\n", sep = "")
    cat("Gene sets tested:   ", nrow(out), "\n")
    cat("Significant (FDR):  ",
        sum(out$p_adj < 0.05, na.rm = TRUE),
        "\n")

  })

  .print_block("Methods selected", function() {

    print(table(out$method))

  })

  .print_block("Top results", function() {

    top <- out[order(out$p_adj), ]

    print(utils::head(top, 5))

  })

  # -------------------------
  # 8. Return
  # -------------------------
  return(invisible(obj))
}
